### ISSUE TITLE
conda installation fails - numpy>=1.14.0 does not work

### ISSUE THREAD

**Issue by dandaman** [dansondergaard/tmhmm.py#11]
Hi @dansondergaard ,

I've set up a clean env to install your tool and installing just your package works, but execution results in this error
```
Traceback (most recent call last):
  File "/home/pgsb/daniel.lang/anaconda3/envs/membrane/lib/python3.6/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/home/pgsb/daniel.lang/anaconda3/envs/membrane/lib/python3.6/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/pgsb/daniel.lang/anaconda3/envs/membrane/lib/python3.6/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.15.4 (/home/ibis/daniel.lang/anaconda3/envs/membrane/lib/python3.6/site-packages), Requirement.parse('numpy<1.14.0,>=1.9.2'), {'scikit-bio'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pgsb/daniel.lang/anaconda3/envs/membrane/bin/tmhmm", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/pgsb/daniel.lang/anaconda3/envs/membrane/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/home/pgsb/daniel.lang/anaconda3/envs/membrane/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/home/pgsb/daniel.lang/anaconda3/envs/membrane/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/pgsb/daniel.lang/anaconda3/envs/membrane/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/pgsb/daniel.lang/anaconda3/envs/membrane/lib/python3.6/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/pgsb/daniel.lang/anaconda3/envs/membrane/lib/python3.6/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.15.4 (/home/ibis/daniel.lang/anaconda3/envs/membrane/lib/python3.6/site-packages), Requirement.parse('numpy<1.14.0,>=1.9.2'), {'scikit-bio'})
```

Forcing downgrading to numpy==1.13.0 solves the problem.

`pip install numpy==1.13.0`

Easy fix would be to adjust the yml...

Thanks for sharing this nice tool - finally an open-source implementation  :+1: 

Best,
Daniel

**Comment by elainfl** [comment]
Dear Dansondergaard, 
I tried to install in your way and I had a similar problem than dandaman's. I tried,
`$ conda create -n testtmhmm -c dansondergaard python=3.5 tmhmm.py`

but I keep having the same problem. It is:

`Traceback (most recent call last):
  File "/home/elena/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/elena/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/elena/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.16.4 (/home/elena/anaconda3/lib/python3.6/site-packages), Requirement.parse('numpy<1.14.0,>=1.9.2'), {'scikit-bio'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elena/anaconda3/bin/tmhmm", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/elena/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/home/elena/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/home/elena/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/elena/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/elena/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/elena/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.16.4 (/home/elena/anaconda3/lib/python3.6/site-packages), Requirement.parse('numpy<1.14.0,>=1.9.2'), {'scikit-bio'})
`
What can I do? 
Thanks

**Comment by dansondergaard** [comment]
Hey, not sure what the problem is here. Haven't had time to look at it. However, I did build new, binary pip packages that can be installed with:

$ pip install tmhmm.py

Only works on Linux, Python versions 3.5, 3.6, and 3.7, though. I'll have a look a re-building the Conda packages later.
