### ISSUE TITLE
ValueError: Not enough values to unpack

### ISSUE THREAD

**Issue by InfoSuresh** [dansondergaard/tmhmm.py#16]
Hi,

I am getting this error.

command: tmhmm -f test.fa -m /TMHMM2.0.model
Traceback (most recent call last):
  File "/usr/local/bin/tmhmm", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/tmhmm/cli.py", line 77, in cli
    for entry in load_fasta_file(args.sequence_file):
  File "/usr/local/lib/python3.7/dist-packages/tmhmm/utils.py", line 52, in load_fasta_file
    append_entry(header, sequence_parts, entries)
  File "/usr/local/lib/python3.7/dist-packages/tmhmm/utils.py", line 38, in append_entry
    id, description = header.split(None, 1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by dansondergaard** [comment]
The headers in your fasta file must have an ID and description, separated
by a space. It seems it doesn't.

**Comment by InfoSuresh** [comment]
Now I am getting this error. I used test fasta file only.
/usr/local/lib/python3.7/dist-packages/tmhmm/api.py:18: RuntimeWarning: divide by zero encountered in log
  _, path = viterbi(sequence, *model)

**Comment by dansondergaard** [comment]
That's not an error, it's just a warning. The output files will be produced
anyway.
