### ISSUE TITLE
"missing 1 required positional argument"

### ISSUE THREAD

**Issue by bosborne** [dansondergaard/tmhmm.py#18]
```
Traceback (most recent call last):
  File "./annotate_with_hmms.py", line 180, in <module>
    main()
  File "./annotate_with_hmms.py", line 48, in main
    annotator.find_tms()
  File "./annotate_with_hmms.py", line 121, in find_tms
    locations = self.run_tmhmm(gb)
  File "./annotate_with_hmms.py", line 125, in run_tmhmm
    annotation, posterior = tmhmm.predict(str(gb.seq), 'TMHMM2.0.model')
TypeError: predict() missing 1 required positional argument: 'model_or_filelike'
```

By the way, `str(gb.seq)` is just protein sequence, not a fasta file name.

**Comment by bosborne** [comment]
```
Traceback (most recent call last):
  File "./annotate_with_hmms.py", line 183, in <module>
    main()
  File "./annotate_with_hmms.py", line 48, in main
    annotator.find_tms()
  File "./annotate_with_hmms.py", line 121, in find_tms
    locations = self.run_tmhmm(gb)
  File "./annotate_with_hmms.py", line 128, in run_tmhmm
    annotation, posterior = tmhmm.predict(seq, header, 'TMHMM2.0.model')
  File "/usr/local/lib/python3.7/site-packages/tmhmm.py-1.3.dev0-py3.7-macosx-10.15-x86_64.egg/tmhmm/api.py", line 16, in predict
    _, model = parse(open(model_or_filelike))
FileNotFoundError: [Errno 2] No such file or directory: 'TMHMM2.0.model'
```
So I added a `header` variable (empty string), don't know what that's supposed to be, but the code can't find the model file now.
